Feat: basic attended transfer impl
WebTrit/webtrit_phone pull request #130
Opened 2024-04-25 12:14 UTC by digiboridev

2024-04-25 12:31 UTC, SERDUN commented on lib/features/call/bloc/call_event.dart
> +      {required ActiveCall referorCall, required ActiveCall transfereeCall}) = _CallControlEventAttendedTransferred;
If we have more than one named parameter, let's use comma+ formatting.

  const factory CallControlEvent.attendedTransferred({
    required ActiveCall referorCall,
    required ActiveCall transfereeCall,
  }) = _CallControlEventAttendedTransferred;

2024-04-26 09:15 UTC, ycherniavskyi requested changes
It seems that some commits descriptions are not following [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) style, please do not forget about it.

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/widgets/popup_item.dart
> +class PopupItem extends PopupMenuItem {
`PopupItem` is confusing call name as for me, which is hard to distinct from Flutter SDK class name, so let's rename it to `CallPopupMenuItem` (the same logic as it done for example for `ExtBackButton`, `ExtTabBar` or `MainAppBar`). This and other popup menu related classed I propose to locate in `popup_menu.dart` file.

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/widgets/popup_menu.dart
> +class PopupMenu extends PopupMenuButton {
`PopupMenu` is confusing call name as for me, which is hard to distinct from Flutter SDK class name, so let's rename it to `CallPopupMenuButton` (the same logic as it done for example for `ExtBackButton`, `ExtTabBar` or `MainAppBar`). This and other popup menu related classed I propose to locate in `popup_menu.dart` file.

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/bloc/call_bloc.dart
> +      );
What is the reason to change formatting in such way? Let's be consistent and use common `emit(state.` formatting when this combination is located in one line.

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/bloc/call_bloc.dart
> +        replaceCallId: transfereeCall.callId,
Do not introduce new naming for entities that already have other naming.
In this case it is `transferee` naming when it is already `replace` naming exist in low level `TransferRequest` class.
So please rename `transfereeCall` variable in all contexts to `replaceCall`.

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/bloc/call_bloc.dart
> -      add(_ResetStateEvent.completeCall(activeCallBlindTransferInitiated.callId));
What is the reason to drop this lines from `__onCallControlEventStarted` method?

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/bloc/call_state.dart
> +  CallState copyWithPushActiveCall(ActiveCall activeCall, {bool? minimized}) {
`minimized` is surplus here.
If you need to change it after this function execution then just use following construction:
```dart
emit(state.copyWithPushActiveCall(ActiveCall(<properties>)).copyWith(minimized: <value>));
```

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/bloc/call_state.dart
> +  List<T> get exceptCurrent => where((activeCall) => activeCall != current).toList();
`exceptCurrent` name is hide actual state of this calls - they are `held`, so let's rename this getter to `held`.
And in implementation let's filter by `activeCall.held` instead of by `current` equality.

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/view/call_active_scaffold.dart
> +    final backgroundCalls = activeCalls.exceptCurrent;
`backgroundCalls` let's rename to `heldCalls`.

2024-04-26 09:15 UTC, ycherniavskyi commented on lib/features/call/widgets/call_actions.dart
> +    final themeData = Theme.of(context);
Usually we put general variable such as `themeData` define before more local ones and separate them by one new line. So please move it before this handle variables block.

2024-04-26 10:39 UTC, digiboridev commented on lib/features/call/bloc/call_state.dart
> +  List<T> get exceptCurrent => where((activeCall) => activeCall != current).toList();
@ycherniavskyi there is reason, because of "orElse: () => last" in current getter. So this list is literaly "except current" not "held"

2024-04-26 10:44 UTC, digiboridev commented on lib/features/call/bloc/call_bloc.dart
> -      add(_ResetStateEvent.completeCall(activeCallBlindTransferInitiated.callId));
@ycherniavskyi this lines i added few days ago, for now i have deeper understanding of flow and rethink its purpose.  I think there is no need to drop active call if transfer request fails, it can be caused by adapter as unrecognized for example, so nothing stops user to just continue active conversation if its possible.

2024-04-26 11:50 UTC, ycherniavskyi commented on lib/features/call/bloc/call_state.dart
> +  List<T> get exceptCurrent => where((activeCall) => activeCall != current).toList();
Clear. In such case I propose to name this getter `notCurrent`.

2024-05-01 14:20 UTC, merged