Сhange style resource
WebTrit/webtrit_phone pull request #14
Opened 2023-05-23 13:17 UTC by SERDUN

2023-06-12 20:49 UTC, ycherniavskyi requested changes

2023-06-12 20:49 UTC, ycherniavskyi commented on packages/style/pubspec.yaml
> +  cupertino_icons: ^1.0.2
This is for sure an odd dependency for this package.

2023-06-12 20:49 UTC, ycherniavskyi commented on packages/style/pubspec.yaml
> +  sdk: '>=2.19.6 <3.0.0'
Update to the last Dart version with the whole branch rebase.

2023-06-12 20:49 UTC, ycherniavskyi commented on packages/style/pubspec.yaml
> +    sdk: flutter
It seems that the `style` package is a pure `Dart` package and could operate without Flutter at all. Am I right?

2023-06-12 20:49 UTC, ycherniavskyi commented on pubspec.yaml
> +  yaml: ^3.1.1
Do we really need to introduce the YAML format to the project just to handle the `publisher.yaml` file? Wouldn't it be simpler and more consistent to store the `publisher` data in a JSON format within a `publisher.json` file instead?

2023-06-12 20:49 UTC, ycherniavskyi commented on lib/app/view/app.dart
> +                title: widget.themeSettings.appName ?? EnvironmentConfig.APP_NAME,
If we're planning on storing the app name in the theme settings, I suggest we remove the `APP_NAME` environment config entirely. The same applies to the `APP_DESCRIPTION` environment config; let's move it to the theme settings instead.

2023-06-12 20:49 UTC, ycherniavskyi commented on lib/features/settings/features/about/view/about_screen.dart
> +                    },
Noticing similar widget structures in several areas is a clear indication that we should consider introducing a dedicated common widget to streamline this functionality.

2023-06-12 20:49 UTC, ycherniavskyi commented on lib/main.dart
> +import 'package:style/style.dart';
Incorrect import order.

2023-06-12 20:49 UTC, ycherniavskyi commented on lib/theme/theme_settings.dart
> +  final String? appName;
What's the reasoning behind the different ordering of constructor parameters and their corresponding instance variable declarations?

2023-06-12 20:49 UTC, ycherniavskyi commented on lib/theme/theme_settings.dart
> +import 'package:webtrit_phone/app/assets.gen.dart';
Missed newline before current import.

2023-06-12 20:49 UTC, ycherniavskyi commented on lib/theme/theme_settings.dart
> +  final applicationLogoStream = ReplaySubject<SvgLoader?>(maxSize: 1);
Is it possible to implement this functionality without `rxdart` primitives?

2023-06-12 20:49 UTC, ycherniavskyi commented on lib/theme/theme_settings.dart
> +  }
What is the reason to make this class mutable with set methods?

2023-06-12 20:49 UTC, ycherniavskyi commented on packages/style/README.md
> +A library for Dart developers.
Not very clear package description 🤷🏻‍♂️.

2023-06-12 20:49 UTC, ycherniavskyi commented on packages/style/lib/src/api/api.dart
> +    if (dart.library.io) '../_http_client/_http_client_io.dart' as platform;
It looks like with the release of [http 1.0.0](https://pub.dev/packages/http/versions/1.0.0), we might be able to eliminate the need for this custom multiplatform solution!

2023-06-13 06:48 UTC, SERDUN commented on packages/style/pubspec.yaml
> +  cupertino_icons: ^1.0.2
Yes, it looks like cupertino_icons is redundant

2023-06-13 06:53 UTC, SERDUN commented on pubspec.yaml
> +  yaml: ^3.1.1
when using yaml, I was guided by the fact that this format is chosen by other plugins for generation, but in our case we don have code generation, we can use generation,I think it would be better to discuss

2023-06-13 06:57 UTC, SERDUN commented on lib/app/view/app.dart
> +                title: widget.themeSettings.appName ?? EnvironmentConfig.APP_NAME,
I agree, but this prompted me to think about how to set the name of the application in the system itself

2023-06-13 07:08 UTC, SERDUN commented on lib/theme/theme_settings.dart
> +  final applicationLogoStream = ReplaySubject<SvgLoader?>(maxSize: 1);
No, i don't know in dart streams about similar behaviour, ReplaySubject emits me last subject after connect to stream builder for example, even if it's happened before

2023-06-13 07:12 UTC, SERDUN commented on lib/theme/theme_settings.dart
> +  }
Because we have several use cases, for phone and for configuration. In configuration i triggered this method when user change resource

2023-09-06 10:01 UTC, SERDUN commented
The requests were divided into several smaller pools

2023-09-06 10:01 UTC, closed without merging