feat: add correct flow with gravatar
WebTrit/webtrit_phone pull request #204
Opened 2024-07-31 09:56 UTC by SERDUN

2024-07-31 09:56 UTC, ycherniavskyi commented
Task linked: [CU-86958uxfp Add correct flow with Gravatar](https://app.clickup.com/t/86958uxfp)

2024-08-06 15:47 UTC, ycherniavskyi requested changes

2024-08-06 15:47 UTC, ycherniavskyi commented on lib/features/contact/view/contact_screen.dart
> +                        thumbnailUrl: contact.thumbnailUrl,
Let's maintain a consistent order for local parameters. In this case, since `thumbnailUrl` is declared after `thumbnail`, let's use the same order during usage.

2024-08-06 15:47 UTC, ycherniavskyi commented on lib/features/contact/view/contact_screen.dart
> +                        thumbnailUrl: contact.thumbnailUrl,
Apply this logic on whole code in this PR, please.

2024-08-06 15:47 UTC, ycherniavskyi commented on lib/features/settings/widgets/user_info_list_tile.dart
> +                  : null,
It seems we need to introduce `lib/utils/gravatar.dart` file with function `Uri? gravatarThumbnailUrl(String? email)`.

2024-08-06 15:47 UTC, ycherniavskyi commented on lib/widgets/leading_avatar.dart
> +  final String? thumbnailUrl;
It is a bit odd that `thumbnailUrl` is passed as `String?` type instead of `Uri?`. Yes, I see that `NetworkImage` requires `url` parameter in `String`, but let's just cast `Uri` to `String` just before passing it to `NetworkImage` constructor.

2024-08-06 15:47 UTC, ycherniavskyi commented on lib/repositories/contacts/contacts_repository.dart
> +        : null;
Here we need to use previously declared `gravatarThumbnailUrl` function.

2024-08-06 15:47 UTC, ycherniavskyi commented on packages/data/app_database/lib/src/app_database.dart
It seems that current change introduce some half backed functionality.
It does not populate returned composed contacts with all email, but only with first one, and also it does not add phones at all.
I cloud propose to left original method in `ContactsDao` as it was before, but add several `*ContactsExt` methods that will return following joining class:
```dart
class ContactWithPhonesAndEmailsData {
  ContactWithEmailData({
    required this.contact,
    this.email,
  });

  final ContactData contact;
  final List<ContactPhoneData> phones;
  final List<ContactEmailData> emails;
}
```

2024-08-07 07:11 UTC, SERDUN commented on packages/data/app_database/lib/src/app_database.dart
But in this case, the original methods will not be used, because the current widgets will need an email

2024-08-12 10:24 UTC, ycherniavskyi requested changes

2024-08-12 10:24 UTC, ycherniavskyi commented on lib/features/contacts/features/contacts_external_tab/view/contacts_external_tab.dart
> +                thumbnailUrl: contact.thumbnailUrl,
It seems that before this line we also need to add `thumbnail: contact.thumbnail,` to be consistent with `view/contacts_local_tab.dart`, even if we know that local contacts do not have binary thumbnail for now.

2024-08-12 10:24 UTC, ycherniavskyi commented on lib/features/contacts/widgets/contact_tile.dart
> +        thumbnailUrl: thumbnailUrl,
Please, put this line after `thumbnail: thumbnail,`, so it will be in the same order as in widget declaration.

2024-08-12 10:24 UTC, ycherniavskyi commented on packages/data/app_database/lib/src/app_database.dart
> +  Stream<List<ContactWithPhonesAndEmailsData>> watchAllContactsWithPhonesAndEmailsExt([
To stay consistent with the naming conventions of other Dao class methods, this method should be named `watchAllContactsExt`. (The purpose of the `ext` suffix can be inferred from the returned class name.)

2024-08-12 13:45 UTC, ycherniavskyi approved these changes

2024-08-12 13:49 UTC, merged