feat: add contact search improvement
WebTrit/webtrit_phone pull request #205
Opened 2024-07-31 15:19 UTC by SERDUN

Use contains for fields with multiple words

Some fields like "firstName" can contain multiple words, such as a full name. In these cases, we should use 'contains' to cover all scenarios.

2024-07-31 15:19 UTC, ycherniavskyi commented
Task linked: [CU-86954cwkw Contact search improvement](https://app.clickup.com/t/86954cwkw)

2024-07-31 17:02 UTC, ycherniavskyi requested changes

2024-07-31 17:02 UTC, ycherniavskyi commented on packages/data/app_database/lib/src/app_database.dart
> -        ].map((c) => c.like('%$searchBit%')).reduce((v, e) => v | e),
Hmm, It seems that the same functionality could be achieved by updating columns map function to `c.lower().like('%${searchBit.toLowerCase()}%')`. If yes then I differently prefer such change that what PR provided currency.

2024-08-01 08:16 UTC, SERDUN commented on packages/data/app_database/lib/src/app_database.dart
> -        ].map((c) => c.like('%$searchBit%')).reduce((v, e) => v | e),
Here's the corrected translation into English:

---

Yesterday, I tried this option, but it didn't help, although logically it should have, given the SQLite queries. We need to check the implementation of the LIKE function; perhaps it works with sequences after all. I agree that the current implementation is somewhat cumbersome. Therefore, I suggest we start by covering this function with tests to simplify debugging, and then continue our investigation.

2024-08-01 13:08 UTC, ycherniavskyi approved these changes

2024-08-01 13:10 UTC, merged