feat: add handler for self-care password expired
WebTrit/webtrit_phone pull request #206
Opened 2024-08-01 18:36 UTC by SERDUN

2024-08-01 18:36 UTC, ycherniavskyi commented
Task linked: [CU-86958met0 Application does not show the real error message](https://app.clickup.com/t/86958met0)

2024-08-01 18:52 UTC, SERDUN commented on lib/blocs/app/app_bloc.dart
> +WebtritApiClient defaultCreateWebtritApiClient(String coreUrl, String tenantId) {
This code is duplicated from the "login" flow. It might make sense to move it to a common place for better code organization and reuse.

2024-08-02 13:01 UTC, ycherniavskyi requested changes

2024-08-02 13:01 UTC, ycherniavskyi commented on lib/blocs/app/app_bloc.dart
> +WebtritApiClient defaultCreateWebtritApiClient(String coreUrl, String tenantId) {
For sure. I propose to move `WebtritApiClientFactory` typedef and `defaultCreateWebtritApiClient` function into  for example `lib/utils/webtrit_api_client.dart` file.

2024-08-02 13:01 UTC, ycherniavskyi commented on lib/blocs/app/app_bloc.dart
> +  void _onLogoutedTeardown(AppLogoutTeardown event, Emitter<AppState> emit) async {
`_onLogoutedTeardown` and `AppLogoutTeardown` why in one name `Logouted` and in other `Logout`?

2024-08-05 08:24 UTC, SERDUN commented
Another point related to this pull request, for my demo task I need an email, which I often have to retrieve through the getUser method. Maybe we should add the user to the application state to avoid making the same requests frequently.

For example:
`  Future<DemoData> _getAction(String tab) async {
    final account = await _webtritApiClient.getUserInfo(_token);
    _logger.info('_prepareRequest: $account');

    return _webtritApiClient.createDemoData(DemoCredential(
      type: _platformInfo.appType,
      identifier: _appInfo.identifier,
      email: account.email!,
      tenantId: _tenantId,
      action: tab,
    ));
  }`

2024-08-05 08:28 UTC, SERDUN commented on lib/blocs/app/app_bloc.dart
> +  void _onLogoutedTeardown(AppLogoutTeardown event, Emitter<AppState> emit) async {
my mistake, thanks, I'll fix it

2024-08-05 08:41 UTC, SERDUN commented
> Another point related to this pull request, for my demo task I need an email, which I often have to retrieve through the getUserInfo method. Maybe we should add the user to the application state to avoid making the same requests frequently.
> 
> For example:
> 
> ```
>   Future<DemoData> _getAction(String tab) async {
>     final account = await _webtritApiClient.getUserInfo(_token);
>     _logger.info('_prepareRequest: $account');
> 
>     return _webtritApiClient.createDemoData(DemoCredential(
>       type: _platformInfo.appType,
>       identifier: _appInfo.identifier,
>       email: account.email!,
>       tenantId: _tenantId,
>       action: tab,
>     ));
>   }
> ```

or maybe just pull email from login flow   void _onLogined(AppLogined event, Emitter<AppState> emit) async {
____
@Freezed(copyWith: false)
class AppLogined with _$AppLogined implements AppEvent {
  const factory AppLogined({
    required String coreUrl,
    required String tenantId,
    required String token,
  }) = _AppLogined;
}

2024-08-06 09:47 UTC, ycherniavskyi approved these changes

2024-08-06 09:47 UTC, merged