fix: correctly handle hangup events for Android background isolates
WebTrit/webtrit_phone pull request #212
Opened 2024-08-19 09:52 UTC by SERDUN

2024-08-19 09:52 UTC, ycherniavskyi commented
Task linked: [CU-8694xtdy8 Cannot decline the call from pop-up notification on Android](https://app.clickup.com/t/8694xtdy8)

2024-08-20 08:12 UTC, ycherniavskyi requested changes

2024-08-20 08:12 UTC, ycherniavskyi commented on lib/background_call_handler.dart
> +    client = await WebtritSignalingClient.connect(signalingUrl, tenantId, token!, true, certs: certificates);
What is the intend of this changes? It seems that nothing actually change from logic point of view.

2024-08-20 08:12 UTC, ycherniavskyi commented on lib/background_call_handler.dart
>      httpClient.connectionTimeout = kSignalingClientConnectionTimeout;
It seems that this code is odd. It create local `httpClient` which is never used.
As I could see instead of this code lines we need to pass `connectionTimeout` property with  `kSignalingClientConnectionTimeout` value to `WebtritSignalingClient.connect` method call.

2024-08-20 08:12 UTC, ycherniavskyi commented on lib/background_call_handler.dart
> +    _logger.warning('_onSignalingEvent $event');
I am not sure this is `warning` message, more likely it is `info` message.

2024-08-20 08:12 UTC, ycherniavskyi commented on lib/background_call_handler.dart
> +    if (handler != null) {
In my opinion, this type of logic is overengineered. Using `runtimeType` instead of `is` is less intuitive. Let's stick with the previous pattern using `if` and `is`. If you really want to write more advanced code, consider using [Dart Patterns](https://dart.dev/language/patterns), specifically [Switch statements and expressions](https://dart.dev/language/patterns#switch-statements-and-expressions).

2024-08-20 08:12 UTC, ycherniavskyi commented on lib/background_call_handler.dart
> +    final lineIndex = _lines.indexWhere((line) => line?.callId == callId);
`line` already mean index, so `lineIndex` is overcomplicated naming which will conflict with other `line` variables names.

2024-08-20 08:12 UTC, ycherniavskyi commented on lib/background_call_handler.dart
>      return defaultValue;
Let's use `else if` structure with brackets here. It is easy to read and more friendly for adding code to some of conditions if needed in future.

2024-08-20 11:35 UTC, SERDUN commented on lib/background_call_handler.dart
>      httpClient.connectionTimeout = kSignalingClientConnectionTimeout;
Yes, you’re right. It’s odd, and I don’t even remember when I added it. Thanks!

2024-08-20 11:48 UTC, SERDUN commented on lib/background_call_handler.dart
>      return defaultValue;
It appears that this function is not being used. I will remove it. Interesting, why didn't the linter highlight it?)

2024-09-17 12:03 UTC, merged