feat: add functionality to close minimized calls when no active call
WebTrit/webtrit_phone pull request #214
Opened 2024-08-21 10:09 UTC by SERDUN

…is present

2024-08-27 09:36 UTC, SERDUN commented
Task linked: https://app.clickup.com/t/8695e03gg

2024-09-30 17:33 UTC, ycherniavskyi requested changes

2024-09-30 17:33 UTC, ycherniavskyi commented on lib/features/call/view/call_active_scaffold.dart
> +                            ),
Hmm, I am not agree with such solution for `CallInfo` widget. I mean make some tiny part of it as other widget container.
Let's get rig of `CallProcessingStatusView` widget completely and inject it into `CallInfo` widget and just pass `status` property in it.

2024-09-30 17:33 UTC, ycherniavskyi commented on lib/features/call/view/call_shell.dart
> +  void _openCallScreen(StackRouter router, CallState state) {
Pass while call state as parameter is to wide here. Let's just use already used `final hasActiveCalls = state.activeCalls.isNotEmpty` local variable pattern and pass `bool hasActiveCalls` parameter instead of `state`.

2024-09-30 17:33 UTC, ycherniavskyi commented on lib/features/call/bloc/call_state.dart
> +    CallProcessingStatus? status,
Let's rename `CallProcessingStatus` to `ActiveCallStatus`.

2024-10-01 12:47 UTC, ycherniavskyi commented on lib/features/call/view/call_active_scaffold.dart
> +                                : const SizedBox(),
That is not what I mean. I propose to put all this widget related code in `CallInfo` widget and instead `callProcessingStatus` property pass `activeCallStatus` property here.

2024-10-01 19:27 UTC, ycherniavskyi approved these changes

2024-10-01 19:28 UTC, merged