feat: add support of embedded tabs
WebTrit/webtrit_phone pull request #233
Opened 2024-09-17 10:29 UTC by SERDUN

2024-09-17 11:44 UTC, ycherniavskyi requested changes

2024-09-17 11:44 UTC, ycherniavskyi commented on lib/features/embedded/extensions/app_router_extension.dart
Odd file name with unnecessary suffix `_extension` and main name not connected to actual extended class - `RouteMatch`.  Let's simply name this file - `route_match.dart`.

2024-09-17 11:44 UTC, ycherniavskyi commented on lib/features/embedded/extensions/app_router_extension.dart
> +extension RequestFailureExension on RouteMatch {
`RequestFailureExension` why?

2024-09-17 11:44 UTC, ycherniavskyi commented on lib/features/embedded/extensions/app_router_extension.dart
> +  RouteMatch? existRouteWIthRequiredParams(PageInfo pageInfo) {
Odd capital `I` in `...WIth...` part of method name.

2024-09-17 11:44 UTC, ycherniavskyi commented on lib/features/main/view/main_screen_page.dart
> +          return _getEmbeddedRoute(flavor);
Let's inline the code of `_getEmbeddedRoute` method here. It will be more easy to read and grasp the logic.

Also rename local variable name `flavor` to `tab`.

2024-09-17 11:44 UTC, ycherniavskyi commented on lib/widgets/webview_scaffold.dart
> +  final WebViewScaffoldOption option;
Separate class `WebViewScaffoldOption` that hold one `bool` variable is for sure overengineering. Just add instance variable `final bool showToolbar` and assign in constructor its default value.

2024-09-17 11:54 UTC, SERDUN commented on lib/features/embedded/extensions/app_router_extension.dart
> +extension RequestFailureExension on RouteMatch {
If we have a new initial screen that requires data, it will be cleaner, in my opinion.

2024-09-18 08:44 UTC, ycherniavskyi commented on screenshots/lib/screenshots/main_screen_screenshot.dart
>  import 'package:webtrit_phone/features/features.dart';
Infort formatting issue, `package:webtrit_phone` must be grouped with `package:webtrit_phone`.

2024-09-18 09:02 UTC, ycherniavskyi approved these changes

2024-09-18 09:02 UTC, merged