feat: improve login flow
WebTrit/webtrit_phone pull request #251
Opened 2024-10-01 14:20 UTC by SERDUN

2024-10-01 20:07 UTC, ycherniavskyi requested changes

2024-10-01 20:07 UTC, ycherniavskyi commented on lib/theme/models/app_config.dart
> +    @Default('') String titleL10n,
Let's not use `''` empty string constant as value with some specific empty meaning. We have null value for that - ` String? titleL10n`.

2024-10-01 20:07 UTC, ycherniavskyi commented on lib/features/login/features/login_embedded/view/login_embedded_screen_page.dart
It is a bit odd to have `LoginEmbeddedScreenPage` (with `LoginEmbedded` prefix) and `EmbeddedLogin` classes in one place related to one functionality.
Could we choose one order from `LoginEmbedded` and `EmbeddedLogin` combinations?

2024-10-01 20:34 UTC, SERDUN commented on lib/theme/models/app_config.dart
> +    @Default('') String titleL10n,
I was thinking about the showToolbar flag. If showToolbar=false, then titleL10n is not necessary, and we can omit it from the schema and skip the additional nullable check in the code

2024-10-01 20:40 UTC, SERDUN commented on lib/features/login/features/login_embedded/view/login_embedded_screen_page.dart
Lets use EmbeddedLogin for order starts with the more general concept (Embedded) followed by the specific feature (Login), which can make it easier to understand that it’s an embedded version of login functionality.

2024-10-02 09:49 UTC, ycherniavskyi approved these changes

2024-10-02 09:50 UTC, merged