Update phone with clarify Contact and expand UserInfo schemas
WebTrit/webtrit_phone pull request #26
Opened 2023-07-31 11:06 UTC by SERDUN

2023-07-31 11:29 UTC, ycherniavskyi requested changes
Within this PR also must be added DB migration for renaming `displayName` to `aliasName`.

2023-07-31 11:29 UTC, ycherniavskyi commented on packages/webtrit_api/test/webtrit_api_test.dart
> -              'display_name': 'display_name_1',
This field didn't remove.

2023-07-31 11:29 UTC, ycherniavskyi commented on packages/webtrit_api/test/webtrit_api_test.dart
>              'last_name': 'last_name_1',
Add `alies_name` field here.

2023-07-31 22:01 UTC, ycherniavskyi requested changes
Also, it seems that you forgot to update the test data with values for added and renamed fields.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/blocs/external_contacts_sync/external_contacts_sync_bloc.dart
> +          aliasName: Value(externalContact.aliasName),
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/contact.dart
> +    this.aliasName,
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/contact.dart
> +  final String? aliasName;
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/contact.dart
> +        aliasName,
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/contact.dart
> +    final displayName = this.aliasName;
Do not forget to also rename the local variable name to `aliasName`.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/external_contact.dart
> +    this.aliasName,
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/external_contact.dart
> +  final String? aliasName;
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/external_contact.dart
> +        aliasName,
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/recent.dart
> +  final String? aliasName;
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/recent.dart
> +    this.aliasName,
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/recent.dart
> +        aliasName,
Add `aliasName` after `lastName` to be consistent.

2023-07-31 22:01 UTC, ycherniavskyi commented on lib/models/recent.dart
> +    final displayName = this.aliasName;
Do not forget to also rename the local variable name to `aliasName`.

2023-08-01 06:53 UTC, SERDUN commented
It seems better not to use idea refactoring when replacing the name and do it by hand, for correctly style

2023-08-01 08:25 UTC, ycherniavskyi commented
> It seems better not to use idea refactoring when replacing the name and do it by hand, for correctly style

Or you could check the result diff before committing 😉.

2023-08-01 15:42 UTC, ycherniavskyi approved these changes

2023-08-01 15:51 UTC, merged