Migrate to WebTrit App ids and configs
WebTrit/webtrit_phone pull request #36
Opened 2023-08-08 06:07 UTC by SERDUN

2023-08-08 06:28 UTC, SERDUN commented
I see that the formatting in the manifest has changed

2023-08-09 08:03 UTC, ycherniavskyi requested changes
@SERDUN, if you've decided to eliminate the functionality of the `WEBTRIT_PHONE_APP_NAME` and `WEBTRIT_PHONE_APP_ID_SUFFIX` environment variables, it should be done consistently across both Android and iOS platforms.

2023-08-09 08:03 UTC, ycherniavskyi commented on android/app/google-services.json
>                  "bundle_id": "com.webtrit.phone"
Why this parameter did not change to `com.webtrit.app`?

2023-08-09 08:03 UTC, ycherniavskyi commented on android/app/build.gradle
> +        minSdkVersion 26 // flutter.minSdkVersion
It seems that `minSdkVersion` must not be increased for this PR.

2023-08-09 12:16 UTC, SERDUN commented
I updated the ios as well, but I'm not sure if I did everything right on the ios side.

2023-08-22 16:19 UTC, ycherniavskyi approved these changes

2023-08-22 16:27 UTC, merged