Feature/launch icons
WebTrit/webtrit_phone pull request #37
Opened 2023-08-08 09:07 UTC by SERDUN

- rename:  logo to primary_onboardin_logo
- added:    secondary_onboardin_logo (for use on different color layouts)

2023-08-09 08:18 UTC, ycherniavskyi requested changes
Is it possible to align resolution of modified assets? If resolution must be changed then please provide links to docs that clarify it.

2023-08-09 08:18 UTC, ycherniavskyi commented on assets/launcher_icons/android.png
Could you please clarify why added asset has a bit strange resolution: W: 415px | H: 415px?

2023-08-09 08:18 UTC, ycherniavskyi commented on assets/launcher_icons/ios.png
The deleted asset was intentionally created with a resolution of W: 1024px | H: 1024px in order to enhance the quality of the assets generated based on it.

2023-08-09 11:18 UTC, SERDUN commented
Android 13:
adaptive icons
1 layer: image: color [108x108]
2 layer: image: color [108x108] ilusration [72x72]+ (better add 16 padding)

Android <13:
icons  image: color [432:432]  for max resolution drawable-xxxhdpi

2023-08-23 11:12 UTC, ycherniavskyi approved these changes

2023-08-23 11:14 UTC, merged