Feature/launch pdf terms
WebTrit/webtrit_phone pull request #52
Opened 2023-11-02 12:59 UTC by SERDUN

2023-11-05 15:55 UTC, ycherniavskyi requested changes

2023-11-05 15:55 UTC, ycherniavskyi commented on ios/Runner/Info.plist
> +		<key>LSApplicationQueriesSchemes~ipad</key>
What is the reason to add `~ipad` to this key?

2023-11-05 15:55 UTC, ycherniavskyi commented on ios/Runner/Info.plist
> +			<string>https</string>
Let's also add `http` value.

2023-11-05 15:55 UTC, ycherniavskyi commented on android/app/src/main/AndroidManifest.xml
> +        </intent>
Let's also add intent for `http` scheme.

2023-11-05 15:55 UTC, ycherniavskyi commented on lib/features/settings/view/settings_screen.dart
> +  void _launchUrl(BuildContext context, Uri uri) async {
The `context` parameter is unnecessary here.
And also let's give this method a more specific name - something like `_launchUrlWithDefaultPlatformViewer`.

2023-11-05 15:55 UTC, ycherniavskyi commented on lib/features/settings/view/settings_screen.dart
> +                  context.pushNamed(MainRoute.settingsTermsConditions);
It seems that we could make some refactoring with this PR, and pass the "terms and conditions URL" as a routing parameter to the `initialUri` property of the `TermsConditionsScreen` widget.

2023-11-06 07:20 UTC, SERDUN commented on ios/Runner/Info.plist
> +		<key>LSApplicationQueriesSchemes~ipad</key>
thank you, I can't understand the world it took, I'll delete it

2023-11-06 07:30 UTC, SERDUN commented on lib/features/settings/view/settings_screen.dart
> +                  context.pushNamed(MainRoute.settingsTermsConditions);
okay ,  good point.
What about key ''initialUrl', should we move it in const ? but i not sure where it better to keep  consts.dart or routes.dart

2023-11-06 08:23 UTC, SERDUN commented on lib/features/settings/view/settings_screen.dart
> +                  context.pushNamed(MainRoute.settingsTermsConditions);
tried to bring out the hard coded values in route queries keys

2023-11-06 18:45 UTC, ycherniavskyi approved these changes

2023-11-06 18:55 UTC, merged