refactor(Android): migrate from using key.property to key.json
WebTrit/webtrit_phone pull request #54
Opened 2023-11-07 12:15 UTC by SERDUN

2023-11-07 14:44 UTC, ycherniavskyi requested changes

2023-11-07 14:44 UTC, ycherniavskyi commented on android/.gitignore
> -key.properties
Let's leave `key.properties` file ignore rule for "backward compatibility" either.

2023-11-07 14:44 UTC, ycherniavskyi commented on android/app/build.gradle
> +def keystoreJson = new JsonSlurper().parse(keystoreJsonFile)
Let's repeat the same functional structure as in the removed code.

2023-11-07 14:44 UTC, ycherniavskyi commented on android/app/build.gradle
> +def keystoreJsonFile = file('../key.json')
I propose to introduce the optional `WEBTRIT_ANDROID_RELEASE_KEY_JSON_PATH` environment variable to pass some external `key.json` file path.

2023-11-07 14:44 UTC, ycherniavskyi commented on android/app/build.gradle
> +            keyAlias keystoreJson.alias
Let's use the same naming as in the release section, so instead of `alias` must be `keyAlias`.

2023-11-07 15:48 UTC, SERDUN commented on android/app/build.gradle
> +def keystoreJson = new JsonSlurper().parse(keystoreJsonFile)
it seems that working with the JsonSlurper class we have a slightly different scenario. in the current case we don't have an exists method but if the file is missing we will have a compile error.

Unable to process file: .../android/key.json (No such file or directory)

if we have a file but there are missing fields, then there will be an error
* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
    > SigningConfig "release" is missing required property "storeFile".
    >SigningConfig "release" is missing required property "storePassword".

2023-11-08 08:14 UTC, SERDUN commented on android/app/build.gradle
> +def keystoreJsonFile = file('../key.json')
I propose to make it even more flexible in this case, and transfer the path not to json but to the package where key.json and upload-keystore.jks are located, it will work well with our key repository, and more flexibly define the path to the keys

2023-11-21 09:47 UTC, ycherniavskyi commented
Reimplemented within ddcc0ef2de613ff76e5320653ce2f0339deca36b.

2023-11-21 09:47 UTC, closed without merging