fix: autoroute.of missing, zone scope, test setup
WebTrit/webtrit_phone pull request #72
Opened 2024-03-22 18:15 UTC by digiboridev

2024-03-25 18:55 UTC, ycherniavskyi requested changes

2024-03-25 18:55 UTC, ycherniavskyi commented on screenshots/android/app/build.gradle
> +        minSdkVersion 26 // flutter.minSdkVersion
Such modification must be provided at least in separate commit with brief explanation of the reason of it. But even better in separate Pull request, because it is not directly related to current PR.

2024-03-25 18:55 UTC, ycherniavskyi commented on screenshots/integration_test/take_screenshots_test.dart
> +  setUpAll(() async {
What is the reason to move this method up? Previously it located before test methods but after helper method `takeScreenshotTestWidgets` - what was wrong with it?

2024-03-25 18:55 UTC, ycherniavskyi commented on screenshots/lib/widgets/screenshot_app.dart
> +import 'package:auto_route/src/router/controller/pageless_routes_observer.dart';
Usually `import` from `src` is undesirable. Do we really need this direct `import`?

2024-03-25 19:18 UTC, digiboridev commented on screenshots/android/app/build.gradle
> +        minSdkVersion 26 // flutter.minSdkVersion
Callkeep requires minsdk26, need extra time to understand why, i support the idea of separate commit.

2024-03-25 19:20 UTC, digiboridev commented on screenshots/integration_test/take_screenshots_test.dart
> +  setUpAll(() async {
its not about position its about do all async work inside setUpAll function before tests. Driver not support async work inside test functions

2024-03-25 19:25 UTC, digiboridev commented on screenshots/lib/widgets/screenshot_app.dart
> +import 'package:auto_route/src/router/controller/pageless_routes_observer.dart';
Yes its bad side of that tipe of fix. I dont know why auto_route hasnt ability to mock its router stack. I think better fix for that its completely get rid of router(low level deps i think) inside shared code, and make dumb reconstruction of screens using decomposition.

2024-03-26 14:54 UTC, digiboridev commented
discard

2024-03-26 14:54 UTC, closed without merging