fix: add limit for keypad size
WebTrit/webtrit_phone pull request #9
Opened 2023-05-12 13:15 UTC by SERDUN

Added limit for keypads items, it's fix most not covered screen size

2023-06-07 21:52 UTC, ycherniavskyi requested changes
Please ensure to implement all applicable feedback from `keypad.dart` in the `actionpad.dart` file as well.

2023-06-07 21:52 UTC, ycherniavskyi commented on lib/features/keypad/widgets/keypad.dart
> +  final void Function(String) onKeypadPressed;
Could you please clarify the rationale for moving this variable before the constructor?
If you're aiming for consistency with `Actionpad`, then our current style guide actually suggests placing instance variables after the constructor in `Actionpad`. Could you consider making this change for alignment with our coding conventions?

2023-06-07 21:52 UTC, ycherniavskyi commented on lib/features/keypad/widgets/keypad.dart
> +  final double _maxSizeLimit = 136;
Could you clarify the source of this constant value? If it originates from a specific place or reasoning, it would be helpful to include a comment with a link or at least a brief explanation.

Additionally, to avoid potential duplication, which we can already see within the file of this pull request, it would be beneficial to move this constant to `lib/app/constants.dart`.

2023-06-07 21:52 UTC, ycherniavskyi commented on lib/features/keypad/widgets/keypad.dart
> +      minimumSize: Size.square(min(MediaQuery.of(context).size.width / 5, _maxSizeLimit)),
This line seems to be doing quite a few operations. To improve readability and clarity, consider introducing a local final variable, perhaps named `dimension`. Assign all these calculations to this variable, then use `dimension` when calling the `Size.square` constructor.

2023-06-08 09:49 UTC, SERDUN commented on lib/features/keypad/widgets/keypad.dart
> +      minimumSize: Size.square(min(MediaQuery.of(context).size.width / 5, _maxSizeLimit)),
Done.

2023-06-08 09:49 UTC, SERDUN commented on lib/features/keypad/widgets/keypad.dart
> +  final double _maxSizeLimit = 136;
Done.

2023-06-08 09:49 UTC, SERDUN commented on lib/features/keypad/widgets/keypad.dart
> +  final void Function(String) onKeypadPressed;
Done.

2023-06-08 13:49 UTC, ycherniavskyi approved these changes

2023-06-08 14:02 UTC, merged